"""Add event_id column to swimmer_event_registration

Revision ID: 080d847913f0
Revises: fb4721764569
Create Date: 2025-06-22 18:32:10.525341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080d847913f0'
down_revision = 'fb4721764569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_swimmer_event_registration_event_id', 'event', ['event_id'], ['id'])
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_swimmer_event_registration_event_id', type_='foreignkey')
        batch_op.drop_column('event_id')
    # ### end Alembic commands ###


    # ### end Alembic commands ###
