"""Add SwimRace model and link to SwimmerEventRegistration

Revision ID: 24ce3eacacc2
Revises: 080d847913f0
Create Date: 2025-06-22 19:18:34.257593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect



# revision identifiers, used by Alembic.
revision = '24ce3eacacc2'
down_revision = '080d847913f0'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)

    if 'swim_race' not in inspector.get_table_names():
        op.create_table(
            'swim_race',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('event_id', sa.Integer(), sa.ForeignKey('event.id')),
            sa.Column('age_group', sa.String(length=20)),
            sa.Column('gender', sa.String(length=20)),
            sa.PrimaryKeyConstraint('id')
        )

    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swim_race_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_swimmer_event_registration_swim_race', 'swim_race', ['swim_race_id'], ['id'])
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_swimmer_event_registration_swim_race', type_='foreignkey')

        batch_op.drop_column('swim_race_id')

    op.drop_table('swim_race')
    # ### end Alembic commands ###
