"""Add age_group_choices to SwimmerEventRegistration

Revision ID: 48c45200ab04
Revises: aec17af47a63
Create Date: 2025-06-26 11:10:35.949599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c45200ab04'
down_revision = 'aec17af47a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group_choices', sa.String(length=100), nullable=True))
        batch_op.drop_column('age_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('age_group_choices')

    # ### end Alembic commands ###
