"""Add age_group_choices field to swimmer_event_registration

Revision ID: 7b1c39d96a46
Revises: 48c45200ab04
Create Date: 2025-06-26 11:12:23.951986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1c39d96a46'
down_revision = '48c45200ab04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.alter_column('age_group_choices',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.alter_column('age_group_choices',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
