"""Add age_group to swimmer_event_registration

Revision ID: aec17af47a63
Revises: 20178bdecb5d
Create Date: 2025-06-26 11:09:31.072739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec17af47a63'
down_revision = '20178bdecb5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swimmer_event_registration', schema=None) as batch_op:
        batch_op.drop_column('age_group')

    # ### end Alembic commands ###
