"""Add n_lanes to Event

Revision ID: ca3711e208c2
Revises: 7b1c39d96a46
Create Date: 2025-07-01 17:37:07.520838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3711e208c2'
down_revision = '7b1c39d96a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_lanes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('n_lanes')

    # ### end Alembic commands ###
