"""Initial migration

Revision ID: fb4721764569
Revises: 
Create Date: 2025-06-22 18:13:01.065238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4721764569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_name', sa.String(length=120), nullable=False),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_temp_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('published_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('place', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('age_groups', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swimmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('emergency_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('sfi_number', sa.String(length=50), nullable=True),
    sa.Column('aadhaar_file', sa.String(length=200), nullable=True),
    sa.Column('sfi_file', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('swimmer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swimmer_phone'), ['phone'], unique=True)

    op.create_table('draft_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('place', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('age_groups', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('place', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('age_groups', sa.Text(), nullable=True),
    sa.Column('registration_start_date', sa.Date(), nullable=True),
    sa.Column('registration_end_date', sa.Date(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('association_name', sa.String(length=200), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('selected_events_json', sa.Text(), nullable=True),
    sa.Column('event_schedule_json', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('full_title', sa.String(length=500), nullable=True),
    sa.Column('max_individual_events', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swimmer_event_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swimmer_id', sa.Integer(), nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['meet_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['swimmer_id'], ['swimmer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swimmer_event_registration')
    op.drop_table('event')
    op.drop_table('draft_event')
    with op.batch_alter_table('swimmer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swimmer_phone'))

    op.drop_table('swimmer')
    op.drop_table('published_event')
    op.drop_table('organizers')
    op.drop_table('admin')
    # ### end Alembic commands ###
